# yamllint configuration file.
# https://yamllint.readthedocs.io/en/stable/

# Extend the default configuration.
extends: default

# Lint rules.
rules:
  line-length:
    level: warning
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  comments:
    min-spaces-from-content: 1
    require-starting-space: false
  document-start:
    present: false
  quoted-strings:
    required: only-when-needed
    extra-allowed: ["{|}"]
  octal-values:
    forbid-implicit-octal: true
  truthy:
    check-keys: false
  key-duplicates: {}
  indentation:
    spaces: 2
