name: Smoke Tests

on:
  workflow_call:
    inputs:
      run_test:
        description: Select desired test
        required: true
        type: string
      target_url:
        description: Base URL for the application
        required: true
        type: string
      user_email:
        description: Test user email
        required: true
        type: string
      user_password:
        description: Test user password
        required: true
        type: string
      course_id:
        description: Course ID to test viewing the course page
        required: true
        type: string
      target_plugins:
        description: Desired plugins to validate
        required: true
        type: string
      unit_id:
        description: Unit ID to test complete-multiplechoice-unit
        required: true
        type: string


jobs:
  check-heartbeat:
    if: ${{ inputs.run_test == 'All' ||  inputs.run_test == 'check-heartbeat'}}
    name: Check Heartbeat
    runs-on: ubuntu-latest

    steps:
      - name: Checkout actions-hub repo
        uses: actions/checkout@v4
        with:
          repository: nelc/actions-hub
          ref: and/add-basic-smoke-tests
          path: actions-hub

      - name: Setup Python and Playwright
        uses: ./actions-hub/.github/actions/setup-playwright

      - name: Run heartbeat test
        run: |
          python actions-hub/scripts/smoke-tests/test_heartbeat.py \
            --base-url "${{ inputs.target_url }}"

  validate-plugins:
    if: ${{ inputs.run_test == 'All' ||  inputs.run_test == 'validate-plugins'}}
    name: Validate eox plugins
    runs-on: ubuntu-latest

    steps:
      - name: Checkout actions-hub repo
        uses: actions/checkout@v4
        with:
          repository: nelc/actions-hub
          ref: and/add-basic-smoke-tests
          path: actions-hub

      - name: Setup Python and Playwright
        uses: ./actions-hub/.github/actions/setup-playwright

      - name: Validate eox plugins
        run: |
          python actions-hub/scripts/smoke-tests/test_eox_plugins.py \
            --base-url "${{ inputs.target_url }}" \
            --plugins ${{ inputs.target_plugins }}

  login-user:
    if: ${{ inputs.run_test == 'All' ||  inputs.run_test == 'login-user'}}
    name: Login User Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout actions-hub repo
        uses: actions/checkout@v4
        with:
          repository: nelc/actions-hub
          ref: and/add-basic-smoke-tests
          path: actions-hub

      - name: Setup Python and Playwright
        uses: ./actions-hub/.github/actions/setup-playwright

      - name: Run login-user test
        run: |
          python actions-hub/scripts/smoke-tests/test_login_user.py \
            --base-url "${{ inputs.target_url }}" \
            --email "${{ inputs.user_email }}" \
            --password "${{ inputs.user_password }}"

  view-course:
    if: ${{ inputs.run_test == 'All' ||  inputs.run_test == 'view-course'}}
    name: View Course Page Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout actions-hub repo
        uses: actions/checkout@v4
        with:
          repository: nelc/actions-hub
          ref: and/add-basic-smoke-tests
          path: actions-hub

      - name: Setup Python and Playwright
        uses: ./actions-hub/.github/actions/setup-playwright

      - name: Run view-course test
        run: |
          python actions-hub/scripts/smoke-tests/test_view_course.py \
            --base-url "${{ inputs.target_url }}" \
            --email "${{ inputs.user_email }}" \
            --password "${{ inputs.user_password }}" \
            --course-id "${{ inputs.course_id }}"

  complete-multiplechoice-unit:
    if: ${{ inputs.run_test == 'All' ||  inputs.run_test == 'complete-multiplechoice-unit'}}
    name: Complete multiplechoice unit test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout actions-hub repo
        uses: actions/checkout@v4
        with:
          repository: nelc/actions-hub
          ref: and/add-basic-smoke-tests
          path: actions-hub

      - name: Setup Python and Playwright
        uses: ./actions-hub/.github/actions/setup-playwright

      - name: Run complete-multiplechoice-unit test
        run: |
          python actions-hub/scripts/smoke-tests/test_complete_multiplechoice_unit.py \
            --base-url "${{ inputs.target_url }}" \
            --email "${{ inputs.user_email }}" \
            --password "${{ inputs.user_password }}" \
            --course-id "${{ inputs.course_id }}" \
            --unit-id "${{ inputs.unit_id }}"

  register-user:
    if: ${{ inputs.run_test == 'All' ||  inputs.run_test == 'register-user'}}
    name: Register user test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout actions-hub repo
        uses: actions/checkout@v4
        with:
          repository: nelc/actions-hub
          ref: and/add-basic-smoke-tests
          path: actions-hub

      - name: Setup Python and Playwright
        uses: ./actions-hub/.github/actions/setup-playwright

      - name: Run register-user test
        run: |
          python actions-hub/scripts/smoke-tests/test_register_user.py \
            --base-url "${{ inputs.target_url }}"
